apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: cms-xcache
  name: cms-xcache-bcache-1-ucsd
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cms-xcache
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: cms-xcache
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - bcache-1.t2.ucsd.edu
      containers:
      - env:
        - name: XC_SITE
          value: UCSD-XCACHE
        - name: XC_RAMSIZE
          value: 25g
        - name: XC_RESOURCENAME
          value: UCSD-XCACHE
        - name: XC_SPACE_LOW_WM
          value: '0.93'
        - name: XC_SPACE_HIGH_WM
          value: '0.97'
        image: opensciencegrid/cms-xcache:stable
        imagePullPolicy: Always
        name: cms-xcache-bcache-1-ucsd
        resources:
           limits:
              memory: 65Gi
              cpu: 25
           requests:
              memory: 56Gi
              cpu: 20
        volumeMounts:
        - mountPath: /etc/osg/image-config.d/00-create-dirs.sh
          name: configinit
          subPath: 00-create-dirs.sh
        - mountPath: /etc/xrootd/config.d/40-cms-xcache-plugin.cfg
          name: config40
          subPath: 40-cms-xcache-plugin.cfg
        - mountPath: /etc/xrootd/config.d/90-node-disks.cfg
          name: config90
          subPath: 90-node-disks.cfg
        - mountPath: /etc/xrootd/config.d/95-local-ucsd.cfg
          name: config95
          subPath: 95-local-ucsd.cfg
        - mountPath: /etc/xrootd/Authfile-cms-xcache
          name: authfile
          subPath: Authfile-cms-xcache
        - mountPath: /etc/supervisord.d/10-cms-xcache.conf
          name: supervisor10
          subPath: 10-cms-xcache.conf 
        - mountPath: /etc/grid-security/hostcert.pem
          name: hostcert
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
        - mountPath: /data1
          name: data1
        - mountPath: /data2
          name: data2
        - mountPath: /xcache-root
          name: localroot
        - mountPath: /xcache-meta
          name: localroot
        - mountPath: /data3
          name: data4
        - mountPath: /data4
          name: data5
        - mountPath: /data5
          name: data6
        - mountPath: /data6
          name: data7
        - mountPath: /data7
          name: data8
        - mountPath: /data8
          name: data9
        - mountPath: /data9
          name: data10
        - mountPath: /data10
          name: data11
        - mountPath: /data11
          name: data12
        - mountPath: /data12
          name: data13
        - mountPath: /data13
          name: data14
        - mountPath: /data14
          name: data15
        - mountPath: /data15
          name: data16
        - mountPath: /data16
          name: data17
        - mountPath: /data17
          name: data18
        - mountPath: /data18
          name: data19
        - mountPath: /data19
          name: data20
        - mountPath: /data20
          name: data21
        - mountPath: /data22
          name: data23
        - mountPath: /data23
          name: data24
        - mountPath: /data24
          name: data25
        - mountPath: /data25
          name: data26
        - mountPath: /data26
          name: data27
        - mountPath: /data28
          name: data29
        - mountPath: /data29
          name: data30
        - mountPath: /data30
          name: data31
        - mountPath: /data31
          name: data32
        - mountPath: /data32
          name: data33
        - mountPath: /data36
          name: data37
        - mountPath: /data37
          name: data38
        - mountPath: /data38
          name: data39
        - mountPath: /data39
          name: data40
        - mountPath: /data40
          name: data41
        - mountPath: /data41
          name: data42
        - mountPath: /data43
          name: data44
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: 00-create-dirs.sh
            path: 00-create-dirs.sh
          name: cms-xcache-bcache-1-ucsd
        name: configinit
      - configMap:
          defaultMode: 420
          items:
          - key: 90-node-disks.cfg
            path: 90-node-disks.cfg
          name: cms-xcache-bcache-1-ucsd
        name: config90
      - configMap:
          defaultMode: 420
          items:
          - key: 95-local-ucsd.cfg
            path: 95-local-ucsd.cfg
          name: cms-xcache-bcache-1-ucsd
        name: config95
      - configMap:
          defaultMode: 420
          items:
          - key: 40-stash-cache-plugin.cfg
            path: 40-cms-xcache-plugin.cfg
          name: cms-xcache-bcache-1-ucsd
        name: config40
      - configMap:
          defaultMode: 420
          items:
          - key: Authfile-cms-xcache
            path: Authfile-cms-xcache
          name: cms-xcache-bcache-1-ucsd
        name: authfile
      - configMap:
          defaultMode: 420
          items:
          - key: 10-cms-xcache-ipv4-cmsd.conf
            path: 10-cms-xcache.conf
          name: cms-xcache-bcache-1-ucsd
        name: supervisor10
      - hostPath:
          path: /etc/grid-security/hostcert.pem
          type: File
        name: hostcert
      - hostPath:
          path: /etc/grid-security/hostkey.pem
          type: File
        name: hostkey
      - name: data1
        hostPath:
          path: /a/1
          type: Directory
      - name: data2
        hostPath:
          path: /a/2
          type: Directory
      - name: data3
        hostPath:
          path: /a/4
          type: Directory
      - name: data4
        hostPath:
          path: /a/5
          type: Directory
      - name: data5
        hostPath:
          path: /a/6
          type: Directory
      - name: data6
        hostPath:
          path: /a/7
          type: Directory
      - name: data7
        hostPath:
          path: /a/8
          type: Directory
      - name: data8
        hostPath:
          path: /a/9
          type: Directory
      - name: data9
        hostPath:
          path: /a/10
          type: Directory
      - name: data10
        hostPath:
          path: /b/1
          type: Directory
      - name: data11
        hostPath:
          path: /b/2
          type: Directory
      - name: data12
        hostPath:
          path: /b/3
          type: Directory
      - name: data13
        hostPath:
          path: /b/4
          type: Directory
      - name: data14
        hostPath:
          path: /b/5
          type: Directory
      - name: data15
        hostPath:
          path: /b/6
          type: Directory
      - name: data16
        hostPath:
          path: /b/7
          type: Directory
      - name: data17
        hostPath:
          path: /b/8
          type: Directory
      - name: data18
        hostPath:
          path: /b/9
          type: Directory
      - name: data19
        hostPath:
          path: /b/10
          type: Directory
      - name: data20
        hostPath:
          path: /c/1
          type: Directory
      - name: data21
        hostPath:
          path: /c/2
          type: Directory
      - name: data23
        hostPath:
          path: /c/4
          type: Directory
      - name: data24
        hostPath:
          path: /c/5
          type: Directory
      - name: data25
        hostPath:
          path: /c/6
          type: Directory
      - name: data26
        hostPath:
          path: /c/7
          type: Directory
      - name: data27
        hostPath:
          path: /c/8
          type: Directory
      - name: data29
        hostPath:
          path: /c/10
          type: Directory
      - name: data30
        hostPath:
          path: /d/1
          type: Directory
      - name: data31
        hostPath:
          path: /d/2
          type: Directory
      - name: data32
        hostPath:
          path: /d/3
          type: Directory
      - name: data33
        hostPath:
          path: /d/4
          type: Directory
      - name: data37
        hostPath:
          path: /d/8
          type: Directory
      - name: data38
        hostPath:
          path: /d/9
          type: Directory
      - name: data39
        hostPath:
          path: /d/10
          type: Directory
      - name: data40
        hostPath:
          path: /e/1
          type: Directory
      - name: data41
        hostPath:
          path: /e/2
          type: Directory
      - name: data42
        hostPath:
          path: /e/3
          type: Directory
      - name: data44
        hostPath:
          path: /a/3
          type: Directory
      - name: localmeta
        hostPath:
          path: /xcache-meta
          type: Directory
      - name: localroot
        hostPath:
          path: /xcache-meta
          type: Directory