apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cms-xcache-bcache-1-ucsd
  namespace: cms-admin
  labels:
    k8s-app: cms-xcache-bcache-1-ucsd
spec:
  template:
    metadata:
      labels:
        k8s-app: cms-xcache-bcache-1-ucsd
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                -  bcache-1.t2.ucsd.edu
      containers:
      - name: cms-xcache-bcache-1-ucsd
        image: efajardo/docker-cms-xcache:latest
        imagePullPolicy: Always
        env:
        - name: XC_SITE
          value: UCSD-XCACHE
        - name: XC_RAMSIZE
          value: 24g
        volumeMounts:
        - name: configinit
          mountPath: /etc/osg/image-config.d/00-create-dirs.sh
          subPath: 00-create-dirs.sh
        - name: config90
          mountPath: /etc/xrootd/config.d/90-node-disks.cfg
          subPath: 90-node-disks.cfg
        - name: config95
          mountPath: /etc/xrootd/config.d/95-local-ucsd.cfg 
          subPath: 95-local-ucsd.cfg 
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
        - mountPath: /data1
          name: data1
        - mountPath: /data2
          name: data2
        - mountPath: /xcache-root
          name: localroot
      volumes:
      - name: configinit
        configMap:
          name: cms-xcache-bcache-1-ucsd
          items:
          - key: 00-create-dirs.sh
            path: 00-create-dirs.sh
      - name: config90
        configMap:
          name: cms-xcache-bcache-1-ucsd
          items:
          - key: 90-node-disks.cfg
            path: 90-node-disks.cfg
      - name: config95
        configMap:
          name: cms-xcache-bcache-1-ucsd
          items:
          - key: 95-local-ucsd.cfg
            path: 95-local-ucsd.cfg
      - name: hostcert
        hostPath:
          path: /etc/grid-security/hostcert.pem
          type: File
      - name: hostkey
        hostPath:
          path: /etc/grid-security/hostkey.pem
          type: File
      - name: data1
        persistentVolumeClaim:
          claimName: pvc-bcache-1-ucsd-s1
      - name: data2
        persistentVolumeClaim:
          claimName: pvc-bcache-1-ucsd-s2
      - name: localroot
        persistentVolumeClaim:
          claimName: pvc-bcache-1-ucsd-s3

